sudo: required

language: perl

perl:
  - "5.16"

addons:
  postgresql: "9.3"

env:
  global:
    - PGVERSION="9.3"
    - JANSSON_VERSION="2.7"
    - BATON_VERSION="0.16.4"
    - SAMTOOLS_VERSION="1.3.1"
    - HTSLIB_VERSION="1.3.2"
    - DISPOSABLE_IRODS_VERSION="1.1"
    - RENCI_FTP_URL=ftp://ftp.renci.org
    - WTSI_NPG_GITHUB_URL=https://github.com/wtsi-npg

  matrix:
    - IRODS_VERSION=3.3.1 IRODS_RIP_DIR=/usr/local/irods
    - IRODS_VERSION=4.1.9 PG_PLUGIN_VERSION=1.9 PLATFORM=ubuntu12

before_install:
  - ./scripts/travis_before_install.sh

install:
  - ./scripts/travis_install.sh

script:
  - export PATH=$IRODS_RIP_DIR/iRODS/clients/icommands/bin:$PATH
  - ienv
  - ils
  - export PATH=$PWD/bin:$PATH
  - ./scripts/travis_script.sh
