dist: bionic

sudo: required

services:
  - docker

language: perl

perl:
  - "5.26"

env:
  global:
    - WSI_NPG_GITHUB_URL=https://github.com/wtsi-npg
    - WSI_CONDA_CHANNEL=https://dnap.cog.sanger.ac.uk/npg/conda/devel/generic/
  matrix:
    - DOCKER_IMAGE="wsinpg/ub-16.04-irods-4.2:latest" IRODS_VERSION="==4.2.7"  BATON_VERSION=">2.0.1" LIBHTS_PLUGINS_VERSION="==201712+irods_4.2.7"

before_install:
  - docker pull "$DOCKER_IMAGE"
  - docker run -d -p 1247:1247 "$DOCKER_IMAGE"
  - docker ps -a
  - ./scripts/travis_before_install.sh

install:
  - ./scripts/travis_install.sh

script:
  - ./scripts/travis_script.sh
