sudo: required

services:
  - docker

language: perl

perl:
  - "5.22-shrplib"

env:
  global:
    - WTSI_NPG_GITHUB_URL=https://github.com/wtsi-npg

before_install:
  - docker pull wsinpg/ub-16.04-irods-4.2
  - docker run -d -p 1247:1247 wsinpg/ub-16.04-irods-4.2
  - docker ps -a
  - ./scripts/travis_before_install.sh

install:
  - ./scripts/travis_install.sh

script:
  - ./scripts/travis_script.sh
